### ISSUE TITLE
Concerning "uBlock filter" and "uBlock filter plus".

### ISSUE THREAD

**Issue by Jose1971AB** [IDKwhattoputhere/uBlock-Filters-Plus#1]
Hello friends...

Excuse me but I am with the help of a translator.

I don't want to report any problems, I just want to report a couple of things.

In third party filters of uBlock origin (or list of filters), above all appears **uBlock filter**, which is a default filter, but in Custom there is another that is added that is **ublock filter plus** (https://raw.githubusercontent.com/IDKwhattoputhere/uBlock-Filters-Plus/master/uBlock-Filters-Plus.txt)

1.- What is the difference between **uBlock filter** and **uBlock filter plus**?

2.- Which is more complete of the two? 

The reason or idea of my question is to leave the most complete, in case one of them was more complete than the other. Correct me but I think it is pointless to leave both if one replaces the other by being more complete.

Thank you very much and greetings

**Comment by Jose1971AB** [comment]
Hello again... Can someone advise me on my question?....

Greetings

**Comment by IDKwhattoputhere** [comment]
They're both completely separate projects, so one is not "more complete" than the other. The built-in lists (the one at the top of the settings page) are updated more frequently though and have more filters so I would expect them to block more too. Hope that answers your question.
