### ISSUE TITLE
Official uBlock Origin filter list

### ISSUE THREAD

**Issue by gorhill** [IDKwhattoputhere/uBlock-Filters-Plus#3]
Often, the solution provided in EasyList/EasyPrivacy to [_"unblocked content"_](https://forums.lanik.us/viewforum.php?f=62) or [_"incorrectly removed content"_](https://forums.lanik.us/viewforum.php?f=62) in EasyList are detrimental to uBlock Origin, because it goes counter to the principle of blocking more, not less in order to decrease the surface area of where a browser connects.

This is really annoying me ([latest example](https://github.com/gorhill/uBlock/commit/9be1700776fb8b969a334f92b94a1a79b8c11574)) -- and I think it's time for uBO to have its own filter list so as to not be crippled by ABP's limitations.

Proposal: to import the list here in a [new repo under my name](https://github.com/gorhill/uAssets), and add you as collaborator (and whoever in the future contributes worthily). I would be merely one of the contributor on that list. 

That list will still be deemed 3rd-party to uBO, but would be enabled out of the box. The content of that list would be uBO's own solutions _if needed_ for issues reported on EasyList. For example, a reported issue can be fixed in uBO with a redirection filter, popunder filter, etc., or whatever capability specific to uBO, while the solution is to create exception filters (thus lowering one's defense) in EasyList. This would be ground to create a filter to cancel EasyList's solution for ABP (using `important` filter option), while using uBO's extra filtering capability to solve the issue in a way that serves user interests better.

I am also considering the creation/maintenance a file which contain the minimal set of rules to "unbreak" sites broken for those using [medium mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode), and also possible other files with set of rules for specific purpose (like foil big ubiquitous 3rd parties, etc), all of which could be simply imported by a user into their _My rules_ pane. This would encourage the use of dynamic filtering, which is probably deserve to be used more.

**Comment by IDKwhattoputhere** [comment]
Sounds like really good ideas. Though I don't yet fully understand what this means for this list. Do I understand correctly that it's supposed to be moved to the new repo in its entirety? And it's going to be selected by default? So this repo would be obsolete and I could remove it afterwards?

**Comment by gorhill** [comment]
I gave more thought on this and I will not import your list as is. Whatever entry in there you think may be beneficial to uBO, an issue should be opened at [uBlockOrigin/uAssets](https://github.com/uBlockOrigin/uAssets), as I want as much as possible every single entry to be documented with a formal issue -- this will be true especially once 1.6.8 is released to AMO, Chrome store, Opera store.

**Comment by IDKwhattoputhere** [comment]
Alright, will do.
