### ISSUE TITLE
uBlock Filters Plus incorrectly blocks a Webopedia page

### ISSUE THREAD

**Issue by anonsubmitter** [IDKwhattoputhere/uBlock-Filters-Plus#5]
uBlock Filters Plus incorrectly blocks [this page](http://www.webopedia.com/TERM/P/popunder.html).

**Comment by IDKwhattoputhere** [comment]
https://github.com/IDKwhattoputhere/uBlock-Filters-Plus/commit/fcb331035617bdfbd1be5babb4eb490798b42275 + https://github.com/IDKwhattoputhere/uBlock-Filters-Plus/commit/97ef8beda06f34f71cd6643e75c1d9a041f363f2
Update in a few minutes and try again.
