### ISSUE TITLE
uBlock Filters Plus blocks parts of antipopads' GitHub repo

### ISSUE THREAD

**Issue by anonsubmitter** [IDKwhattoputhere/uBlock-Filters-Plus#6]
uBlock Filters Plus blocks https://github.com/Yhonay/antipopads/blob/master/popads.txt

Whitelist filter rule:
`/popads.$document,domain=~github.com`

**Comment by IDKwhattoputhere** [comment]
Thanks, should be fixed now. https://github.com/IDKwhattoputhere/uBlock-Filters-Plus/commit/d791d2eadb7800cb288047b47fee9cfba4cf9f12
