### ISSUE TITLE
www.chip.de

### ISSUE THREAD

**Issue by sdfasdfgawe456h4356** [IDKwhattoputhere/uBlock-Filters-Plus#9]
http://www.chip.de/news/Game-of-Thrones-Staffel-6-kommt-ins-Free-TV_108301383.html

with your filter list enabled the website doesnt load
it shows a warning that something prevents the website from loading

thx

**Comment by IDKwhattoputhere** [comment]
Can you try if these filters work? Just add them in uBlock Origin's settings.
```
||p.w.*.com/s/err
||contributor.google.com/scripts/*/loader.js$script,domain=chip.de
```

**Comment by IDKwhattoputhere** [comment]
I added the filters. https://github.com/IDKwhattoputhere/uBlock-Filters-Plus/commit/65d20908485862e9b646fd3d6b3b089c3b25bc2b
Please comment below if they break something or if it's not working for you.
